### ISSUE TITLE
Vector Ensembler Code

### ISSUE THREAD

**Issue by inovatek** [commonsense/conceptnet-numberbatch#37]
Hello

Here we see the Dataset where can I find the Numberbatch Vector Ensembler Code ?

Thank you very much.

**Comment by rspeer** [comment]
The previous version had code at: https://github.com/commonsense/conceptnet-numberbatch/tree/16.04/code -- I should include a link to that in the README.

The current version is integrated with the development version of the ConceptNet code: https://github.com/commonsense/conceptnet5/tree/version5.5/conceptnet5/vectors

**Comment by inovatek** [comment]
Thank you very much ! 

Really appreciate sharing it !!

Yanky
