### ISSUE TITLE
Wrong link for the first file to download

### ISSUE THREAD

**Issue by mitbal** [commonsense/conceptnet-numberbatch#40]
Hi, I found that the link for file uris_main point to this location http://conceptnet5.media.mit.edu/downloads/conceptnet-numberbatch-16.09/conceptnet-numberbatch-201609_en_extra.txt.gz

However, I believe it should be pointed to this location. http://conceptnet5.media.mit.edu/downloads/conceptnet-numberbatch-16.09/conceptnet-numberbatch-201609_uris_main.txt.gz

**Comment by rspeer** [comment]
Thanks for pointing that out!
