### ISSUE TITLE
downloads and term vectors not available

### ISSUE THREAD

**Issue by timofeytt** [commonsense/conceptnet-numberbatch#42]
Your links are not working. I'm trying to download any of the following:
conceptnet-numberbatch-201609_uris_main.txt.gz (1928481 × 300) contains terms from many languages, specified by their complete ConceptNet URI (the strings starting with /c/en/ in the example above).

conceptnet-numberbatch-201609_en_main.txt.gz (426572 × 300) contains only English terms, and strips the /c/en/ prefix to provide just the term text. This form is the most compatible with other systems, as long as you only want English.

conceptnet-numberbatch-201609_en_extra.txt.gz (233488 × 300) contains additional single words of English whose vectors could be inferred as the average of their neighbors in ConceptNet.

conceptnet-numberbatch-201609.h5 contains the data in its native HDF5 format, which can be loaded with the Python library pandas.

http://conceptnet5.media.mit.edu/downloads/ is also not working.

**Comment by rspeer** [comment]
Oh, I see why. Should be straightforward to fix.

**Comment by rspeer** [comment]
Fixed now. Thanks for the report.
