### ISSUE TITLE
number batch code

### ISSUE THREAD

**Issue by meghmehta** [commonsense/conceptnet-numberbatch#44]
Hi,

I've run the code over the whole weekend but it still has not completed. You had mentioned it would take about a day to run... do you think there was something that happened incorrectly?

Thanks,

Megh

**Comment by rspeer** [comment]
What's happening? Has it computed any results in the `build-data` directory? Is it possible that you're out of RAM and swapping (which will slow things down by orders of magnitude)?

Also, if I can ask, what's your goal in reproducing this particular evaluation? If it's for the sake of the science, you should probably use a later version that actually got published. And if you have custom data you want to incorporate, then you don't have to run all the conditions to reproduce a data table in an unpublished paper.

**Comment by meghmehta** [comment]
No, I still don't have a build-data directory....I wanted to incorporate custom data and then have a look at the vectors produced...

**Comment by rspeer** [comment]
Okay, so you could save some pain by modifying the code to just build one matrix, not all the matrices we ever evaluated.

But it sounds like you aren't even able to compute a single matrix. Is it just swapping or what?

In general I'd encourage you to update to the published build process, incorporated in ConceptNet 5.5: https://github.com/commonsense/conceptnet5/wiki/Build-process . But if you have problems with a lack of computing resources you're still going to have them.

**Comment by meghmehta** [comment]
Okay thanks - so where can I add my own vectors? Also where could I change so that I only build one matrix? Thanks for the help!

**Comment by meghmehta** [comment]
The code finished running but there is still no build-data folder containing any output....

**Comment by rspeer** [comment]
You would add your own vectors by changing the conceptnet5 code. There isn't a neatly-packaged process for it. Feel free to contribute it if you come up with one.

If you want me to keep trying to debug your run of this old version of conceptnet-numberbatch, you're going to have to tell me what it *did* output, not just what it didn't output.
