### ISSUE TITLE
Common word subset

### ISSUE THREAD

**Issue by ncammarata** [commonsense/conceptnet-numberbatch#47]
Is it possible to download a subset of Numberbatch sorted by common words? In my application, it is computationally infeasible to load all of the words into memory. 

However, a 20% subset of the most common words would solve my problems and fit into memory as well. 

Please let me know if this is possible!
Nick

**Comment by jlowryduda** [comment]
Hi! This is not currently available, but may be in the future. If you want to sort Numberbatch yourself, you could use `wordfreq` library.

**Comment by ncammarata** [comment]
That's a surprisingly simple answer that I hadn't though of. Thanks!
