### ISSUE TITLE
@paper is not recognized while importing citation

### ISSUE THREAD

**Issue by yigitsever** [commonsense/conceptnet-numberbatch#53]
Hello,
The citation you provided in readme threw an error while I was importing it to zotero.
I couldn't find anything related to a `@paper` entry, I believe the following is the correct (updated?) form.

```
@inproceedings{speer2017conceptnet,
  title = {{{ConceptNet}} 5.5: {{An Open Multilingual Graph}} of {{General Knowledge}}},
  url = {http://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14972},
  eventtitle = {{{AAAI Conference}} on {{Artificial Intelligence}}},
  date = {2017},
  pages = {4444-4451},
  author = {Speer, Robyn and Chin, Joshua and Havasi, Catherine}
}
```

**Comment by rspeer** [comment]
Okay, thanks. I wonder what gave me the form including `@paper`.

What's the reason for the doubled-up braces, by the way? I see that I need one set of braces to preserve the capitalization of ConceptNet; I don't see a reason to preserve the capitalization of An Open Multilingual Graph etc, so I wouldn't include those. But what does the second pair of braces do?

**Comment by yigitsever** [comment]
Sorry! Apparently better bibtex (for zotero) includes them, I exported the same entry in bibtex format;

```
@inproceedings{speer2017conceptnet,
	title = {{ConceptNet} 5.5: An Open Multilingual Graph of General Knowledge},
	url = {http://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14972},
	author = {Speer, Robyn and Chin, Joshua and Havasi, Catherine},
	year = {2017},
	pages = {4444--4451}
}
```

**Comment by rspeer** [comment]
Okay, neat, just wanted to make sure I wasn't missing something else. I'll use that as the citation. Thanks!
