### ISSUE TITLE
Embedding for other dimensions: 50, 100 and 200

### ISSUE THREAD

**Issue by zhongpeixiang** [commonsense/conceptnet-numberbatch#58]
It's really nice to see concept-enriched embeddings!

It would be nicer to have embeddings in other dimensions, e.g., 50, 100 and 200 because there are many models that use these smaller dimensions to prevent overfitting.

**Comment by lsorber** [comment]
You could use PCA [1] to reduce the dimensionality to however many dimensions you wish. The embeddings start to degrade around the 200 mark though.

[1] https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

**Comment by zhongpeixiang** [comment]
Thanks for pointing out using PAC for dimension reduction :).
